/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 adidas.gltf --transform
Author: Fsartorelli (https://sketchfab.com/fsartorelli)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/shoes-adidas-raleigh-mid-dd1f489dd8074dd58997fe711d4ca7f6
Title: Shoes Adidas Raleigh Mid
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('/adidas-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <group position={[-0.04, -3.26, 7.36]} rotation={[3.06, 0, 0.01]} scale={0.01}>
        <mesh geometry={nodes.Object_2.geometry} material={materials.Material_0} />
        <mesh geometry={nodes.Object_3.geometry} material={materials.Material_0} />
      </group>
    </group>
  )
}

useGLTF.preload('/adidas-transformed.glb')
